### ISSUE TITLE
Config-seed always loads every possible config

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/core-config-seed#32] opened 2018-01-27 21:42 UTC
The current config seed loads all of its configs when it runs, including all existing device services (as of Barcelona release).  It also always loads both the docker and non-docker config for each service.  I originally ran into this while working on my edgex core snap, but managed to reproduce as well by starting up the default Barcelona services via the developer-script run-it script.

**Comment by tonyespy** [comment] 2018-01-27 21:44
![consul-config](https://user-images.githubusercontent.com/5264713/35476649-56002f16-0381-11e8-8d22-e90786020daa.png)

**Comment by xmlviking** [comment] 2018-06-27 16:37
So I think this is by design for the current up to California release.  We most certainly can address this issue post California release.

**Comment by tsconn23** [comment] 2018-06-27 22:26
I think this issue pre-dates some of the discussions we've had around streamlining configuration. For Delhi, we're looking at creating a v2 tree in Consul that will include a standardized set of keys for each service. The key will NOT be specific to a particular implementation and/or deployment profile (as it is now), but rather the implementation will have to conform to the keys.

**Comment by eb-oss** [comment] 2019-02-05 20:59
Closing issue; repo is being archived.

**Closed as completed by eb-oss** 2019-02-05 20:59 UTC
